//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZySharp.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZySharp.Validation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of argument &apos;{0}&apos; must be derived from &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeDerivedFromType {
            get {
                return ResourceManager.GetString("ArgumentMustBeDerivedFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of argument &apos;{0}&apos; must be derived from [{1}]..
        /// </summary>
        internal static string ArgumentMustBeDerivedFromTypes {
            get {
                return ResourceManager.GetString("ArgumentMustBeDerivedFromTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be equal to the value of argument `{1}`. Values: &apos;{0}&apos; = &apos;{2}&apos;, &apos;{1}&apos; = &apos;{3}&apos;.
        /// </summary>
        internal static string ArgumentMustBeEqualToReference {
            get {
                return ResourceManager.GetString("ArgumentMustBeEqualToReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be greater than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be greater than or equal to the value of argument `{1}`. Values: &apos;{0}&apos; = &apos;{2}&apos;, &apos;{1}&apos; = &apos;{3}&apos;.
        /// </summary>
        internal static string ArgumentMustBeGreaterThanOrEqualToReference {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualToReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be greater than the value of argument `{1}`. Values: &apos;{0}&apos; = &apos;{2}&apos;, &apos;{1}&apos; = &apos;{3}&apos;.
        /// </summary>
        internal static string ArgumentMustBeGreaterThanReference {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be in range [&apos;{1}&apos;..&apos;{2}&apos;]..
        /// </summary>
        internal static string ArgumentMustBeInRange {
            get {
                return ResourceManager.GetString("ArgumentMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be less than &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeLessThan {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be less than or equal to &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be less than or equal to the value of argument `{1}`. Values: &apos;{0}&apos; = &apos;{2}&apos;, &apos;{1}&apos; = &apos;{3}&apos;.
        /// </summary>
        internal static string ArgumentMustBeLessThanOrEqualToReference {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThanOrEqualToReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be less than the value of argument `{1}`. Values: &apos;{0}&apos; = &apos;{2}&apos;, &apos;{1}&apos; = &apos;{3}&apos;.
        /// </summary>
        internal static string ArgumentMustBeLessThanReference {
            get {
                return ResourceManager.GetString("ArgumentMustBeLessThanReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be used mutually exclusive to the argument &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeMutuallyExclusive {
            get {
                return ResourceManager.GetString("ArgumentMustBeMutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of argument &apos;{0}&apos; must be &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeOfType {
            get {
                return ResourceManager.GetString("ArgumentMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of argument &apos;{0}&apos; must be [{1}]..
        /// </summary>
        internal static string ArgumentMustBeOfTypes {
            get {
                return ResourceManager.GetString("ArgumentMustBeOfTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be one of [{1}]..
        /// </summary>
        internal static string ArgumentMustBeOneOf {
            get {
                return ResourceManager.GetString("ArgumentMustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must be &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustBeValue {
            get {
                return ResourceManager.GetString("ArgumentMustBeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of argument &apos;{0}&apos; must not be derived from &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustNotBeDerivedFromType {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeDerivedFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of argument &apos;{0}&apos; must not be derived from [{1}]..
        /// </summary>
        internal static string ArgumentMustNotBeDerivedFromTypes {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeDerivedFromTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must not be empty..
        /// </summary>
        internal static string ArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must not be equal to the value of argument `{1}`. Values: &apos;{0}&apos; = &apos;{2}&apos;, &apos;{1}&apos; = &apos;{3}&apos;.
        /// </summary>
        internal static string ArgumentMustNotBeEqualToReference {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEqualToReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must not be &apos;null&apos;..
        /// </summary>
        internal static string ArgumentMustNotBeNull {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must not be &apos;null&apos; or empty..
        /// </summary>
        internal static string ArgumentMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must not be of type &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustNotBeOfType {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must not be of type [{1}]..
        /// </summary>
        internal static string ArgumentMustNotBeOfTypes {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeOfTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must not be one of [{1}]..
        /// </summary>
        internal static string ArgumentMustNotBeOneOf {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must not be &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentMustNotBeValue {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must contain only distinct values. Duplicate keys: [{1}]..
        /// </summary>
        internal static string EnumerableMustBeDistinct {
            get {
                return ResourceManager.GetString("EnumerableMustBeDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given expression &apos;{0}&apos; must be a member-expression..
        /// </summary>
        internal static string ExpressionMustBeMemberExpression {
            get {
                return ResourceManager.GetString("ExpressionMustBeMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current reference must not contain a &apos;null&apos; value..
        /// </summary>
        internal static string ReferenceMustNotContainNullValue {
            get {
                return ResourceManager.GetString("ReferenceMustNotContainNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a readable stream..
        /// </summary>
        internal static string StreamMustBeReadable {
            get {
                return ResourceManager.GetString("StreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a seekable stream..
        /// </summary>
        internal static string StreamMustBeSeekable {
            get {
                return ResourceManager.GetString("StreamMustBeSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be a writeable stream..
        /// </summary>
        internal static string StreamMustBeWriteable {
            get {
                return ResourceManager.GetString("StreamMustBeWriteable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; must match the pattern &apos;{1}&apos;..
        /// </summary>
        internal static string StringMustMatchPattern {
            get {
                return ResourceManager.GetString("StringMustMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be an absolute URI..
        /// </summary>
        internal static string UriMustBeAbsolute {
            get {
                return ResourceManager.GetString("UriMustBeAbsolute", resourceCulture);
            }
        }
    }
}
